/**
 * ----------------------------------------------------------------------------
 * Summary:
 * This file sets up the global middleware for authentication using NextAuth.js.
 *
 * - Imports the `auth` middleware helper generated in auth.config.ts.
 * - Exports a default middleware function that runs on every matched request.
 * - Ensures authentication and authorization rules defined in the auth config
 *   are applied at the edge before serving any protected pages.
 *
 * In short, this file activates the NextAuth authentication middleware so
 * that all protected routes behave correctly across the application.
 * ----------------------------------------------------------------------------
 */

// Imports the `auth` helper generated by NextAuth() in auth.config.ts. This contains authentication, session handling, and route protection logic.
import { auth } from "./auth.config";

/**
 * Exports the NextAuth authentication middleware as the default function.
 *
 * The `auth` wrapper internally:
 * - Runs the `authorized` callback defined in auth.config.ts.
 * - Creates or updates session cookies.
 * - Protects routes based on your regex patterns.
 *
 * Since no additional logic is needed here, we simply export `auth` directly.
 */
export default auth;
